services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16.6
    environment:
      POSTGRES_USER: ziko
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shopdjango
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

volumes:
  pg_data:
