# Generated by Django 5.1.1 on 2024-10-07 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_options'),
        ('configurate', '0002_alter_productconfiguration_car_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configurate.productconfiguration', verbose_name='Конфигурация'),
        ),
    ]
