# Generated by Django 5.1.1 on 2024-10-07 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cart_configuration'),
        ('goods', '0003_alter_categories_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.products', verbose_name='Товар'),
        ),
    ]
