# Generated by Django 5.1.1 on 2024-10-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurate', '0002_alter_productconfiguration_car_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productconfiguration',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
