# Generated by Django 5.1.1 on 2024-10-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurate', '0003_productconfiguration_sell_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productconfiguration',
            options={'ordering': ('id',), 'verbose_name': 'Комплектация', 'verbose_name_plural': 'Комплектации'},
        ),
        migrations.RemoveField(
            model_name='productconfiguration',
            name='quantity',
        ),
        migrations.AddField(
            model_name='productconfiguration',
            name='quantity_available',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество в наличии'),
        ),
        migrations.AlterField(
            model_name='productconfiguration',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Цена продажи'),
        ),
    ]
