# Generated by Django 5.1.1 on 2024-10-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurate', '0004_alter_productconfiguration_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productconfiguration',
            name='quantity_available',
        ),
        migrations.AddField(
            model_name='productconfiguration',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество в наличии'),
        ),
    ]
