# Generated by Django 5.1.1 on 2024-10-07 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurate', '0005_remove_productconfiguration_quantity_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productconfiguration',
            old_name='quantity',
            new_name='quantity_available',
        ),
    ]
