# Generated by Django 5.1.4 on 2024-12-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurate', '0006_rename_quantity_productconfiguration_quantity_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productconfiguration',
            name='carpet_color',
            field=models.CharField(blank=True, choices=[('Czarny', 'Czarny'), ('Grafitowy', 'Grafitowy'), ('Czekoladowy', 'Czekoladowy'), ('Kremowy', 'Kremowy'), ('Atramentowy', 'Atramentowy'), ('Burgund', 'Burgund'), ('Chabrowy', 'Chabrowy'), ('Cytrynowy', 'Cytrynowy'), ('Limonkowy', 'Limonkowy'), ('Czerwony', 'Czerwony'), ('Malachitowy', 'Malachitowy'), ('Orzechowy', 'Orzechowy'), ('Pomarańczowy', 'Pomarańczowy'), ('Purpurowy', 'Purpurowy'), ('Różowy', 'Różowy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='productconfiguration',
            name='color',
            field=models.CharField(blank=True, choices=[('Czarny', 'Czarny'), ('Grafitowy', 'Grafitowy'), ('Srebrny', 'Srebrny'), ('Biały', 'Biały'), ('Cytrynowy', 'Cytrynowy'), ('Pomarańczowy', 'Pomarańczowy'), ('Czerwony', 'Czerwony'), ('Ciemno chabrowy', 'Ciemno chabrowy'), ('Chabrowy', 'Chabrowy'), ('Jasno chabrowy', 'Jasno chabrowy'), ('Jagodowy', 'Jagodowy'), ('Purpurowy', 'Purpurowy'), ('Liliowy', 'Liliowy'), ('Różowy', 'Różowy'), ('Kremowy', 'Kremowy'), ('Ciemno czekoladowy', 'Ciemno czekoladowy'), ('Jasno czekoladowy', 'Jasno czekoladowy'), ('Miedziany', 'Miedziany'), ('Malachitowy', 'Malachitowy'), ('Khaki', 'Khaki'), ('Limonkowy', 'Limonkowy'), ('Zielony', 'Zielony'), ('Burgund', 'Burgund')], max_length=100),
        ),
    ]
