COMPLETE_SET_CHOICES = [
    ("Wybierz komplet", "Wybierz komplet"),
    (
        "ETC Zestaw 2D (przód, tył, tunel) - 390 PLN",
        "ETC Zestaw 2D (przód, tył, tunel) - 390 PLN",
    ),
    ("ETC Zestaw przód 2D - 250 PLN", "ETC Zestaw przód 2D - 250 PLN"),
    ("ETC Zestaw tył 2D - 200 PLN", "ETC Zestaw tył 2D - 200 PLN"),
    ("Nie potrzebuję dywaników tylko matę", "Nie potrzebuję dywaników tylko matę"),
]

MAT_CHOICES = [
    ("Nie potrzebuję maty", "Nie potrzebuję maty"),
    ("Mata do bagażnika - 300 PLN", "Mata do bagażnika - 300 PLN"),
]

SHAPE_CHOICES = [
    ("Romby", "Romby"),
    ("Soty", "Soty"),
]

COLOR_CHOICES = [
    ("Czarny", "Czarny"),
    ("Grafitowy", "Grafitowy"),
    ("Srebrny", "Srebrny"),
    ("Biały", "Biały"),
    ("Cytrynowy", "Cytrynowy"),
    ("Pomarańczowy", "Pomarańczowy"),
    ("Czerwony", "Czerwony"),
    ("Ciemno chabrowy", "Ciemno chabrowy"),
    ("Chabrowy", "Chabrowy"),
    ("Jasno chabrowy", "Jasno chabrowy"),
    ("Jagodowy", "Jagodowy"),
    ("Purpurowy", "Purpurowy"),
    ("Liliowy", "Liliowy"),
    ("Różowy", "Różowy"),
    ("Kremowy", "Kremowy"),
    ("Ciemno czekoladowy", "Ciemno czekoladowy"),
    ("Jasno czekoladowy", "Jasno czekoladowy"),
    ("Miedziany", "Miedziany"),
    ("Malachitowy", "Malachitowy"),
    ("Khaki", "Khaki"),
    ("Limonkowy", "Limonkowy"),
    ("Zielony", "Zielony"),
    ("Burgund", "Burgund"),
]

CARPET_CHOICES = [
    ("Czarny", "Czarny"),
    ("Grafitowy", "Grafitowy"),
    ("Czekoladowy", "Czekoladowy"),
    ("Kremowy", "Kremowy"),
    ("Atramentowy", "Atramentowy"),
    ("Burgund", "Burgund"),
    ("Chabrowy", "Chabrowy"),
    ("Cytrynowy", "Cytrynowy"),
    ("Limonkowy", "Limonkowy"),
    ("Czerwony", "Czerwony"),
    ("Malachitowy", "Malachitowy"),
    ("Orzechowy", "Orzechowy"),
    ("Pomarańczowy", "Pomarańczowy"),
    ("Purpurowy", "Purpurowy"),
    ("Różowy", "Różowy"),
]

CAR_BRAND_CHOICES = [
    ("Wiberz", "Wiberz auto"),
    ("Abarth", "Abarth"),
    ("Acura", "Acura"),
    ("Alfa Romeo", "Alfa Romeo"),
    ("Aston Martin", "Aston Martin"),
    ("Aixam", "Aixam"),
    ("Audi", "Audi"),
    ("Bentley", "Bentley"),
    ("BMW", "BMW"),
    ("Cadillac", "Cadillac"),
    ("Chevrolet", "Chevrolet"),
    ("Chrysler", "Chrysler"),
    ("Citroën", "Citroën"),
    ("Cupra", "Cupra"),
    ("Dacia", "Dacia"),
    ("Daewoo", "Daewoo"),
    ("Dodge", "Dodge"),
    ("DS", "DS"),
    ("Ferrari", "Ferrari"),
    ("Fisker", "Fisker"),
    ("Ford", "Ford"),
    ("FSO Polonez", "FSO Polonez"),
    ("GMC", "GMC"),
    ("Honda", "Honda"),
    ("Hummer", "Hummer"),
    ("Hyundai", "Hyundai"),
    ("Infinity", "Infinity"),
    ("Isuzu", "Isuzu"),
    ("Iveco", "Iveco"),
    ("Jaguar", "Jaguar"),
    ("Jeep", "Jeep"),
    ("Kia", "Kia"),
    ("Lamborghini", "Lamborghini"),
    ("Lancia", "Lancia"),
    ("Land Rover", "Land Rover"),
    ("Lexus", "Lexus"),
    ("Lincoln", "Lincoln"),
    ("Lotus", "Lotus"),
    ("Lublin", "Lublin"),
    ("Mazda", "Mazda"),
    ("McLaren", "McLaren"),
    ("Mercedes-Benz", "Mercedes-Benz"),
    ("MG", "MG"),
    ("Mini", "Mini"),
    ("Mitsubishi", "Mitsubishi"),
    ("Nissan", "Nissan"),
    ("Opel", "Opel"),
    ("Peugeot", "Peugeot"),
    ("Porsche", "Porsche"),
    ("Renault", "Renault"),
    ("Rolls Royce", "Rolls Royce"),
    ("Rover", "Rover"),
    ("SaaB", "SaaB"),
    ("Scion", "Scion"),
    ("Seat", "Seat"),
    ("Skoda", "Skoda"),
    ("Smart", "Smart"),
    ("SsangYong", "SsangYong"),
    ("Subaru", "Subaru"),
    ("Suzuki", "Suzuki"),
    ("Tesla", "Tesla"),
    ("Toyota", "Toyota"),
    ("Volkswagen", "Volkswagen"),
    ("Volvo", "Volvo"),
]

CAR_MODEL_CHOICES = {
    "Abarth": [
        ("Abarth Grande Punto Hatchback", "Abarth Grande Punto Hatchback"),
        ("Abarth 124 Spider Cabrio", "Abarth 124 Spider Cabrio"),
        ("Abarth 500 Hatchback", "Abarth 500 Hatchback"),
    ],
    "Acura": [
        ("Acura MDX SUV", "Acura MDX SUV"),
        ("Acura TSX CU2 Sedan", "Acura TSX CU2 Sedan"),
        ("Acura TL Sedan", "Acura TL Sedan"),
    ],
    "Alfa Romeo": [
        ("Alfa Romeo 156 Kombi", "Alfa Romeo 156 Kombi"),
        ("Alfa Romeo 156 Sedan", "Alfa Romeo 156 Sedan"),
        ("Alfa Romeo 156 Crosswagon Kombi", "Alfa Romeo 156 Crosswagon Kombi"),
        ("Alfa Romeo 159 Kombi", "Alfa Romeo 159 Kombi"),
        ("Alfa Romeo 159 Sedan", "Alfa Romeo 159 Sedan"),
        ("Alfa Romeo Giulietta Hatchback", "Alfa Romeo Giulietta Hatchback"),
        ("Alfa Romeo Giulia Sedan", "Alfa Romeo Giulia Sedan"),
        ("Alfa Romeo Mito Hatchback", "Alfa Romeo Mito Hatchback"),
        ("Alfa Romeo Spider Cabrio", "Alfa Romeo Spider Cabrio"),
        ("Alfa Romeo Brera Coupe", "Alfa Romeo Brera Coupe"),
        ("Alfa Romeo Stelvio SUV", "Alfa Romeo Stelvio SUV"),
        ("Alfa Romeo 147 Hatchback", "Alfa Romeo 147 Hatchback"),
        ("Alfa Romeo Tonale SUV", "Alfa Romeo Tonale SUV"),
        ("Alfa Romeo GT Goupe", "Alfa Romeo GT Goupe"),
        ("Alfa Romeo 166 Sedan", "Alfa Romeo 166 Sedan"),
    ],
    "Aston Martin": [
        (
            "Aston Martin DB11 Volante Kabrioet",
            "Aston Martin DB11 Volante Kabrioet",
        ),
        ("Aston Martin DB11 Coupe", "Aston Martin DB11 Coupe"),
        (
            "Aston Martin DB12 Volante Kabriolet",
            "Aston Martin DB12 Volante Kabriolet",
        ),
        ("Aston Martin DB12 Volante Coupe", "Aston Martin DB12 Volante Coupe"),
        ("Aston Martin DBS Kabriolet", "Aston Martin DBS Kabriolet"),
        ("Aston Martin DBS Coupe", "Aston Martin DBS Coupe"),
        ("Aston Martin DBX SUV", "Aston Martin DBX SUV"),
        ("Aston Martin Rapide Liftback", "Aston Martin Rapide Liftback"),
        ("Aston Martin Vantage V8 Coupe", "Aston Martin Vantage V8 Coupe"),
        ("Aston Martin Vantage V8 Roadster", "Aston Martin Vantage V8 Roadster"),
        ("Aston Martin Vantage V12 Coupe", "Aston Martin Vantage V12 Coupe"),
        ("Aston Martin Vantage V12 Roadster", "Aston Martin Vantage V12 Roadster"),
        (
            "Aston Martin Vantage V12 Speedster",
            "Aston Martin Vantage V12 Speedster",
        ),
        ("Aston Martin Vanquish Coupe", "Aston Martin Vanquish Coupe"),
        ("Aston Martin Vanquish Coupe-S", "Aston Martin Vanquish Coupe-S"),
        ("Aston Martin Vanquish Roadster", "Aston Martin Vanquish Roadster"),
        ("Aston Martin Vanquish Roaster-S", "Aston Martin Vanquish Roaster-S"),
        ("Aston Martin Vulcan Coupe", "Aston Martin Vulcan Coupe"),
    ],
    "Aixam": [
        ("Aixam City67", "Aixam City67"),
        ("Aixam Crossline21", "Aixam Crossline21"),
        ("Aixam Coupe19", "Aixam Coupe19"),
        ("Aixam Crossover15", "Aixam Crossover15"),
        ("Aixam Other12", "Aixam Other12"),
        ("Aixam GTO4", "Aixam GTO4"),
        ("Aixam A7412", "Aixam A7412"),
    ],
    "Audi": [
        ("Audi A1 Hatchback", "Audi A1 Hatchback"),
        ("Audi A3 Hatchback", "Audi A3 Hatchback"),
        ("Audi A3 Cabrio", "Audi A3 Cabrio"),
        ("Audi A3 S-Line Hatchback", "Audi A3 S-Line Hatchback"),
        ("Audi A3 Sedan", "Audi A3 Sedan"),
        (
            "Audi A3 S-Line Sportback Hatchback",
            "Audi A3 S-Line Sportback Hatchback",
        ),
        ("Audi A3 Sportback Hatchback", "Audi A3 Sportback Hatchback"),
        ("Audi A4 B5 Kombi", "Audi A4 B5 Kombi"),
        ("Audi A4 B5 Sedan", "Audi A4 B5 Sedan"),
        ("Audi A4 B6 Kombi", "Audi A4 B6 Kombi"),
        ("Audi A4 B6 Sedan", "Audi A4 B6 Sedan"),
        ("Audi A4 B7 Cabrio", "Audi A4 B7 Cabrio"),
        ("Audi A4 B7 Kombi", "Audi A4 B7 Kombi"),
        ("Audi A4 B7 Sedan", "Audi A4 B7 Sedan"),
        ("Audi A4 S-Line B7 Kombi", "Audi A4 S-Line B7 Kombi"),
        ("Audi A4 S-Line B7 Sedan", "Audi A4 S-Line B7 Sedan"),
        ("Audi A4 Allroad B8 Kombi", "Audi A4 Allroad B8 Kombi"),
        ("Audi A4 Avant B8 Kombi", "Audi A4 Avant B8 Kombi"),
        ("Audi A4 B8 Sedan", "Audi A4 B8 Sedan"),
        ("Audi A4 S-Line B8 Sedan", "Audi A4 S-Line B8 Sedan"),
        ("Audi A4 B9 Kombi", "Audi A4 B9 Kombi"),
        ("Audi A4 B9 Sedan", "Audi A4 B9 Sedan"),
        ("Audi A5 Coupe", "Audi A5 Coupe"),
        ("Audi A5 Sportback Liftback", "Audi A5 Sportback Liftback"),
        ("Audi A5 Cabrio", "Audi A5 Cabrio"),
        ("Audi S5 Coupe", "Audi S5 Coupe"),
        ("Audi S5 Cabrio", "Audi S5 Cabrio"),
        ("Audi S5 Sportback Liftback", "Audi S5 Sportback Liftback"),
        ("Audi A6 C5 Kombi", "Audi A6 C5 Kombi"),
        ("Audi A6 C5 Sedan", "Audi A6 C5 Sedan"),
        ("Audi A6 C6 Kombi", "Audi A6 C6 Kombi"),
        ("Audi A6 C6 Sedan", "Audi A6 C6 Sedan"),
        ("Audi A6 C7 Kombi", "Audi A6 C7 Kombi"),
        ("Audi A6 C7 Sedan", "Audi A6 C7 Sedan"),
        ("Audi A6 Allroad C8 Kombi", "Audi A6 Allroad C8 Kombi"),
        ("Audi A6 C8 Kombi", "Audi A6 C8 Kombi"),
        ("Audi A6 C8 Sedan", "Audi A6 C8 Sedan"),
        ("Audi A7 4G8 Liftback", "Audi A7 4G8 Liftback"),
        ("Audi A7 S-Line 4G8 Liftback", "Audi A7 S-Line 4G8 Liftback"),
        ("Audi A7 4k8 Liftback", "Audi A7 4k8 Liftback"),
        ("Audi A8 D2 Sedan Short", "Audi A8 D2 Sedan Short"),
        ("Audi A8 S-Line D2 Sedan Short", "Audi A8 S-Line D2 Sedan Short"),
        ("Audi A8 D3 Sedan Long", "Audi A8 D3 Sedan Long"),
        ("Audi A8 D3 Sedan Short", "Audi A8 D3 Sedan Short"),
        ("Audi A8 S-Line D3 Sedan Long", "Audi A8 S-Line D3 Sedan Long"),
        ("Audi A8 S-Line D3 Sedan Short", "Audi A8 S-Line D3 Sedan Short"),
        ("Audi A8 D4 Sedan Long", "Audi A8 D4 Sedan Long"),
        ("Audi A8 D4 Sedan Short", "Audi A8 D4 Sedan Short"),
        ("Audi A8 D5 Sedan Long", "Audi A8 D5 Sedan Long"),
        ("Audi A8 D5 Sedan Short", "Audi A8 D5 Sedan Short"),
        ("Audi Q2 SUV", "Audi Q2 SUV"),
        ("Audi Q3 8U SUV", "Audi Q3 8U SUV"),
        ("Audi Q3 S-Line 8U SUV", "Audi Q3 S-Line 8U SUV"),
        ("Audi Q3 F3 SUV", "Audi Q3 F3 SUV"),
        ("Audi Q3 sportback F3 SUV", "Audi Q3 sportback F3 SUV"),
        ("Audi Q5 8R SUV", "Audi Q5 8R SUV"),
        ("Audi Q5 FY SUV", "Audi Q5 FY SUV"),
        ("Audi Q5 Sportback FY SUV", "Audi Q5 Sportback FY SUV"),
        ("Audi Q5 USA FY SUV", "Audi Q5 USA FY SUV"),
        ("Audi Q7 USA FY SUV", "Audi Q7 USA FY SUV"),
        ("Audi Q7 5-osobowy SUV", "Audi Q7 5-osobowy SUV"),
        ("Audi Q7 7-osobowy SUV", "Audi Q7 7-osobowy SUV"),
        ("Audi S6 C5 Kombi", "Audi S6 C5 Kombi"),
        ("Audi S6 C5 Sedan", "Audi S6 C5 Sedan"),
        ("Audi Q8 SUV", "Audi Q8 SUV"),
        ("Audi E-TRON SUV", "Audi E-TRON SUV"),
        ("Audi E-TRON GT Sedan", "Audi E-TRON GT Sedan"),
        ("Audi RS5 F5 Coupe", "Audi RS5 F5 Coupe"),
        ("Audi RS6 C7 Kombi", "Audi RS6 C7 Kombi"),
        ("Audi RS6 C8 Kombi", "Audi RS6 C8 Kombi"),
        ("Audi TT 8J Coupe", "Audi TT 8J Coupe"),
        ("Audi TT 8S Coupe", "Audi TT 8S Coupe"),
        ("Audi RS3 Sportback 8V Hatchback", "Audi RS3 Sportback 8V Hatchback"),
        ("Audi A2 Hatchback", "Audi A2 Hatchback"),
        ("Audi 80 B3 Sedan", "Audi 80 B3 Sedan"),
        ("Audi 80 B4 Cabrio", "Audi 80 B4 Cabrio"),
        ("Audi 80 B4 Sedan", "Audi 80 B4 Sedan"),
        ("Audi Q4 E-Tron SUV", "Audi Q4 E-Tron SUV"),
        ("Audi 100 C3 Sedan", "Audi 100 C3 Sedan"),
        ("Audi 100 C4 Sedan", "Audi 100 C4 Sedan"),
        ("Audi S3 Hatchback", "Audi S3 Hatchback"),
        ("Audi S3 8Y Hatchback", "Audi S3 8Y Hatchback"),
        ("Audi RS Q3 sportback SUV", "Audi RS Q3 sportback SUV"),
        ("Audi Q8 E-TRON SUV", "Audi Q8 E-TRON SUV"),
    ],
    "Bentley": [
        ("Bentley Bentayga SUV", "Bentley Bentayga SUV"),
        ("Bentley Bentayga EWB SUV", "Bentley Bentayga EWB SUV"),
        (
            "Bentley Continental Flying Spur Sedan",
            "Bentley Continental Flying Spur Sedan",
        ),
        ("Bentley Continental GT Kabriolet", "Bentley Continental GT Kabriolet"),
        ("Bentley Continental GT Coupe", "Bentley Continental GT Coupe"),
        ("Bentley Flying Spur Sedan", "Bentley Flying Spur Sedan"),
        ("Bentley Mulsanne EWD Sedan", "Bentley Mulsanne EWD Sedan"),
        ("Bentley Mulsanne Sedan", "Bentley Mulsanne Sedan"),
    ],
    "BMW": [
        ("1", "BMW 1"),
        ("2", "BMW 2"),
        ("2002", "BMW 2002"),
        ("3", "BMW 3"),
        ("3 GT", "BMW 3 GT"),
        ("4", "BMW 4"),
        ("5", "BMW 5"),
        ("5 GT", "BMW 5 GT"),
        ("6", "BMW 6"),
        ("7", "BMW 7"),
        ("8", "BMW 8"),
        ("i3", "BMW i3"),
        ("i4", "BMW i4"),
        ("i8", "BMW i8"),
        ("iX", "BMW iX"),
        ("iX3", "BMW iX3"),
        ("M2", "BMW M2"),
        ("M3", "BMW M3"),
        ("M4", "BMW M4"),
        ("M5", "BMW M5"),
        ("M8", "BMW M8"),
        ("X1", "BMW X1"),
        ("X2", "BMW X2"),
        ("X3", "BMW X3"),
        ("X4", "BMW X4"),
        ("X5M", "BMW X5M"),
        ("X6", "BMW X6"),
        ("X7", "BMW X7"),
        ("Z3", "BMW Z3"),
        ("Z4", "BMW Z4"),
    ],
    "Cadillac": [
        ("Cadillac CTS Sedan", "Cadillac CTS Sedan"),
        ("Cadillac Eldorado Coupe", "Cadillac Eldorado Coupe"),
        ("Cadillac Escalade SUV", "Cadillac Escalade SUV"),
        ("Cadillac Escalade 7-osobowy SUV", "Cadillac Escalade 7-osobowy SUV"),
        ("Cadillac XTS Sedan", "Cadillac XTS Sedan"),
        (
            "Cadillac Escalade ESV 7-osobowy SUV",
            "Cadillac Escalade ESV 7-osobowy SUV",
        ),
        ("Cadillac Escalade ESV SUV", "Cadillac Escalade ESV SUV"),
        ("Cadillac SPX SUV", "Cadillac SPX SUV"),
    ],
    "Chevrolet": [
        ("Chevrolet Aveo T250 Hatchback", "Chevrolet Aveo T250 Hatchback"),
        ("Chevrolet Aveo T250 Sedan", "Chevrolet Aveo T250 Sedan"),
        ("Chevrolet T300 Hatchback", "Chevrolet T300 Hatchback"),
        ("Chevrolet T300 3 gen Sedan", "Chevrolet T300 3 gen Sedan"),
        ("Chevrolet Corvette C3 Coupe", "Chevrolet Corvette C3 Coupe"),
        ("Chevrolet Corvette C5 Cabrio", "Chevrolet Corvette C5 Cabrio"),
        ("Chevrolet Corvette C6 Coupe", "Chevrolet Corvette C6 Coupe"),
        ("Chevrolet Corvette C7 Coupe", "Chevrolet Corvette C7 Coupe"),
        ("Chevrolet Corvette USA C8 Cabrio", "Chevrolet Corvette USA C8 Cabrio"),
        ("Chevrolet Cruze Hatchback", "Chevrolet Cruze Hatchback"),
        ("Chevrolet Cruze Kombi", "Chevrolet Cruze Kombi"),
        ("Chevrolet Cruze Sedan", "Chevrolet Cruze Sedan"),
        ("Chevrolet Cruze J400 Sedan", "Chevrolet Cruze J400 Sedan"),
        ("Chevrolet Evanda Sedan", "Chevrolet Evanda Sedan"),
        ("Chevrolet Suburban SUV", "Chevrolet Suburban SUV"),
        (
            "Chevrolet Chevrolet Suburban 7-osobowy SUV",
            "Chevrolet Chevrolet Suburban 7-osobowy SUV",
        ),
        ("Chevrolet Camaro Coupe", "Chevrolet Camaro Coupe"),
        ("Chevrolet Camaro Sport ZL1 Coupe", "Chevrolet Camaro Sport ZL1 Coupe"),
        (
            "Chevrolet Camaro Transformer edition ZL1 Coupe",
            "Chevrolet Camaro Transformer edition ZL1 Coupe",
        ),
        ("Chevrolet Rezzo/Tacuma KombiVan", "Chevrolet Rezzo/Tacuma KombiVan"),
        ("Chevrolet Spark Hatchback", "Chevrolet Spark Hatchback"),
        (
            "Chevrolet Aveo/Kalos T200 Hatchback",
            "Chevrolet Aveo/Kalos T200 Hatchback",
        ),
        ("Chevrolet Aveo/Kalos T200 Sedan", "Chevrolet Aveo/Kalos T200 Sedan"),
        ("Chevrolet Tahoe SUV", "Chevrolet Tahoe SUV"),
        ("Chevrolet Tahoe 6-osobowy SUV", "Chevrolet Tahoe 6-osobowy SUV"),
        ("Chevrolet Express Van", "Chevrolet Express Van"),
        ("Chevrolet Malibu Sedan", "Chevrolet Malibu Sedan"),
        ("Chevrolet Orlando 7-osobowy SUV", "Chevrolet Orlando 7-osobowy SUV"),
        ("Chevrolet Lacetti J200 Hatchback", "Chevrolet Lacetti J200 Hatchback"),
        ("Chevrolet Captiva 7-osobowy SUV", "Chevrolet Captiva 7-osobowy SUV"),
        ("Chevrolet Nubira Kombi", "Chevrolet Nubira Kombi"),
        ("Chevrolet Cobalt Sedan", "Chevrolet Cobalt Sedan"),
        ("Chevrolet Trailblazer SUV", "Chevrolet Trailblazer SUV"),
        ("Chevrolet Trax SUV 5 drzwi", "Chevrolet Trax SUV 5 drzwi"),
    ],
    "Chrysler": [
        ("Chrysler 200", "Chrysler 200"),
        ("Chrysler 300", "Chrysler 300"),
        ("Chrysler Aspen", "Chrysler Aspen"),
        ("Chrysler Grand Voyager", "Chrysler Grand Voyager"),
        ("Chrysler New Yorker", "Chrysler New Yorker"),
        ("Chrysler Pacifica", "Chrysler Pacifica"),
        ("Chrysler Pacifica Pinnacle", "Chrysler Pacifica Pinnacle"),
        ("Chrysler PT Cruiser", "Chrysler PT Cruiser"),
        ("Chrysler Sebring", "Chrysler Sebring"),
        ("Chrysler Stratus", "Chrysler Stratus"),
        ("Chrysler Town & Country", "Chrysler Town & Country"),
        ("Chrysler Voyager", "Chrysler Voyager"),
    ],
    "Citroën": [
        ("Citroën AX", "Citroën AX"),
        ("Citroën Berlingo", "Citroën Berlingo"),
        ("Citroën C-Crosser", "Citroën C-Crosser"),
        ("Citroën C-Elysee", "Citroën C-Elysee"),
        ("Citroën C1", "Citroën C1"),
        ("Citroën C2", "Citroën C2"),
        ("Citroën C3", "Citroën C3"),
        ("Citroën C3 Aircross", "Citroën C3 Aircross"),
        ("Citroën C3 Picasso", "Citroën C3 Picasso"),
        ("Citroën C4", "Citroën C4"),
        ("Citroën C4 Cactus", "Citroën C4 Cactus"),
        ("Citroën C4 Grand Picasso", "Citroën C4 Grand Picasso"),
        ("Citroën C4 Picasso", "Citroën C4 Picasso"),
        ("Citroën C5", "Citroën C5"),
        ("Citroën C5 Aircross", "Citroën C5 Aircross"),
        ("Citroën C5X", "Citroën C5X"),
        ("Citroën C8", "Citroën C8"),
        ("Citroën DS3", "Citroën DS3"),
        ("Citroën DS4", "Citroën DS4"),
        ("Citroën DS5", "Citroën DS5"),
        ("Citroën Jumper", "Citroën Jumper"),
        ("Citroën Jumpy", "Citroën Jumpy"),
        ("Citroën SpaceTourer", "Citroën SpaceTourer"),
        ("Citroën XM", "Citroën XM"),
        ("Citroën Xsara Picasso", "Citroën Xsara Picasso"),
    ],
    "Cupra": [
        ("Cupra Ateca", "Cupra Ateca"),
        ("Cupra Born", "Cupra Born"),
        ("Cupra Formentor", "Cupra Formentor"),
        ("Cupra Leon", "Cupra Leon"),
    ],
    "Dacia": [
        ("Dacia Dokker", "Dacia Dokker"),
        ("Dacia Duster", "Dacia Duster"),
        ("Dacia Jogger", "Dacia Jogger"),
        ("Dacia Lodgy", "Dacia Lodgy"),
        ("Dacia Logan", "Dacia Logan"),
        ("Dacia Sandero", "Dacia Sandero"),
        ("Dacia Spring", "Dacia Spring"),
    ],
    "Daewoo": [
        ("Daewoo Espero Sedan", "Daewoo Espero Sedan"),
        ("Daewoo Matiz Hatchback", "Daewoo Matiz Hatchback"),
        ("Daewoo Tico Hatchback", "Daewoo Tico Hatchback"),
        ("Daewoo Lanos Hatchback", "Daewoo Lanos Hatchback"),
    ],
    "Dodge": [
        ("Dodge Avenger", "Dodge Avenger"),
        ("Dodge Caliber", "Dodge Caliber"),
        ("Dodge Challenger", "Dodge Challenger"),
        ("Dodge Charger", "Dodge Charger"),
        ("Dodge Dart", "Dodge Dart"),
        ("Dodge Durango", "Dodge Durango"),
        ("Dodge Durango R/T", "Dodge Durango R/T"),
        ("Dodge Grand Caravan", "Dodge Grand Caravan"),
        ("Dodge Grand Caravan GT", "Dodge Grand Caravan GT"),
        ("Dodge Grand Caravan R/T", "Dodge Grand Caravan R/T"),
        ("Dodge Magnum", "Dodge Magnum"),
        ("Dodge Ram", "Dodge Ram"),
    ],
    "DS": [
        ("DS 7 Crossback SUV", "DS 7 Crossback SUV"),
        ("DS 4 Hatchback", "DS 4 Hatchback"),
        ("DS 9 Sedan", "DS 9 Sedan"),
        ("DS 5 Hatchback", "DS 5 Hatchback"),
    ],
    "Ferrari": [
        ("360-1-gen-coupe", "Ferrari 360 1 gen Coupe"),
    ],
    "FIAT": [
        ("126", "FIAT 126"),
        ("500", "FIAT 500"),
        ("500-new", "FIAT 500 new"),
        ("500e", "FIAT 500E"),
        ("500l", "FIAT 500L"),
        ("500x", "FIAT 500X"),
        ("barchetta", "FIAT Barchetta"),
        ("bravo", "FIAT Bravo"),
        ("coupe", "FIAT Coupe"),
        ("croma", "FIAT Croma"),
        ("doblo", "FIAT Doblo"),
        ("ducato", "FIAT Ducato"),
        ("fiorino", "FIAT Fiorino"),
        ("freemont", "FIAT Freemont"),
        ("fullback", "FIAT Fullback"),
        ("grande-punto", "FIAT Grande Punto"),
        ("linea", "FIAT Linea"),
        ("panda", "FIAT Panda"),
        ("punto", "FIAT Punto"),
        ("qubo", "FIAT Qubo"),
        ("sedici", "FIAT Sedici"),
        ("seicento", "FIAT Seicento"),
        ("siena", "FIAT Siena"),
        ("stilo", "FIAT Stilo"),
        ("talento", "FIAT Talento"),
        ("tipo", "FIAT Tipo"),
        ("tipo-cross", "FIAT Tipo Cross"),
        ("uno", "FIAT Uno"),
    ],
    "Fisker": [
        ("karma-hybryda-sedan", "Fisker Karma Hybryda Sedan"),
    ],
    "Ford": [
        ("c-max", "Ford C-Max"),
        ("ecosport", "Ford Ecosport"),
        ("edge", "Ford Edge"),
        ("escape", "Ford Escape"),
        ("escort", "Ford Escort"),
        ("expedition", "Ford Expedition"),
        ("explorer", "Ford Explorer"),
        ("f-150", "Ford F-150"),
        ("fiesta", "Ford Fiesta"),
        ("fiesta-active", "Ford Fiesta Active"),
        ("fiesta-st", "Ford Fiesta ST"),
        ("flex", "Ford Flex"),
        ("focus", "Ford Focus"),
        ("focus-st", "Ford Focus ST"),
        ("fusion", "Ford Fusion"),
        ("galaxy", "Ford Galaxy"),
        ("grand-c-max", "Ford Grand C-Max"),
        ("grand-tourneo-connect", "Ford Grand Tourneo Connect"),
        ("ka", "Ford KA"),
        ("ka-plus", "Ford KA+"),
        ("kuga", "Ford Kuga"),
        ("maverick", "Ford Maverick"),
        ("mondeo", "Ford Mondeo"),
        ("mustang", "Ford Mustang"),
        ("mustang-mach-e", "Ford Mustang Mach-E"),
        ("puma", "Ford Puma"),
        ("ranger", "Ford Ranger"),
        ("ranger-raptor", "Ford Ranger Raptor"),
        ("raptor", "Ford Raptor"),
        ("s-max", "Ford S-Max"),
        ("tourneo-connect", "Ford Tourneo Connect"),
        ("tourneo-courier", "Ford Tourneo Courier"),
        ("tourneo-custom", "Ford Tourneo Custom"),
        ("transit", "Ford Transit"),
        ("transit-courier", "Ford Transit Courier"),
        ("transit-custom", "Ford Transit Custom"),
    ],
    "FSO Polonez": [
        ("caro-hatchback", "FSO Polonez Caro Hatchback"),
    ],
    "GMC": [
        ("acadia-7-osobowy-suv", "GMC Acadia 7-osobowy SUV"),
    ],
    "Honda": [
        ("accord", "Honda Accord"),
        ("city", "Honda City"),
        ("civic", "Honda Civic"),
        ("cr-v", "Honda CR-V"),
        ("cr-x", "Honda CR-X"),
        ("cr-z", "Honda CR-Z"),
        ("element", "Honda Element"),
        ("fr-v", "Honda FR-V"),
        ("hr-v", "Honda HR-V"),
        ("insight", "Honda Insight"),
        ("jazz", "Honda Jazz"),
        ("jazz-crosstar", "Honda Jazz Crosstar"),
        ("nsx", "Honda NSX"),
        ("odyssey", "Honda Odyssey"),
        ("pilot", "Honda Pilot"),
    ],
    "Hummer": [
        ("h2-6-osobowy-suv", "Hummer H2 6-osobowy SUV"),
        ("h3-suv", "Hummer H3 SUV"),
    ],
    "Hyundai": [
        ("coupe", "Hyundai Coupe"),
        ("elantra", "Hyundai Elantra"),
        ("genesis", "Hyundai Genesis"),
        ("getz", "Hyundai Getz"),
        ("grand-santa-fe", "Hyundai Grand Santa Fe"),
        ("h1", "Hyundai H1"),
        ("i10", "Hyundai I10"),
        ("i10n", "Hyundai I10N"),
        ("i20", "Hyundai I20"),
        ("i20n", "Hyundai I20N"),
        ("i30", "Hyundai I30"),
        ("i30n", "Hyundai I30N"),
        ("i40", "Hyundai I40"),
        ("ioniq", "Hyundai Ioniq"),
        ("ioniq-5", "Hyundai Ioniq 5"),
        ("ix20", "Hyundai IX20"),
        ("ix35", "Hyundai IX35"),
        ("kona", "Hyundai Kona"),
        ("palisade", "Hyundai Palisade"),
        ("santa-fe", "Hyundai Santa Fe"),
        ("sonata", "Hyundai Sonata"),
        ("terracan", "Hyundai Terracan"),
        ("tucson", "Hyundai Tucson"),
        ("veloster", "Hyundai Veloster"),
        ("veloster-turbo", "Hyundai Veloster Turbo"),
    ],
    "Infinity": [
        ("fx", "Infinity FX"),
        ("m", "Infinity M"),
        ("q30", "Infinity Q30"),
        ("q50", "Infinity Q50"),
        ("q60", "Infinity Q60"),
        ("q70", "Infinity Q70"),
        ("qx30", "Infinity QX30"),
        ("qx70", "Infinity QX70"),
        ("qx70s", "Infinity QX70S"),
        ("qx80", "Infinity QX80"),
    ],
    "Isuzu": [
        ("d-max-double-cab-pick-up", "Isuzu D-Max Double Cab Pick-up"),
    ],
    "Iveco": [
        ("d-max-double-cab-pick-up", "Isuzu D-Max Double Cab Pick-up"),
    ],
    "Jaguar": [
        ("e-pace", "Jaguar E-Pace"),
        ("f-pace", "Jaguar F-Pace"),
        ("s-type", "Jaguar S-type"),
        ("x-type", "Jaguar X-Type"),
        ("xe", "Jaguar XE"),
        ("xf", "Jaguar XF"),
        ("xk", "Jaguar XK"),
    ],
    "Jeep": [
        ("avenger", "Jeep Avenger"),
        ("cherokee", "Jeep Cherokee"),
        ("commander", "Jeep Commander"),
        ("compass", "Jeep Compass"),
        ("gladiator", "Jeep Gladiator"),
        ("grand-cherokee", "Jeep Grand Cherokee"),
        ("liberty", "Jeep Liberty"),
        ("patriot", "Jeep Patriot"),
        ("renegade", "Jeep Renegade"),
        ("renegade-4xe", "Jeep Renegade 4Xe"),
        ("wrangler", "Jeep Wrangler"),
        ("wrangler-rubicon", "Jeep Wrangler Rubicon"),
    ],
    "Kia": [
        ("carens", "Kia Carens"),
        ("carnival", "Kia Carnival"),
        ("ceed", "Kia Ceed"),
        ("clarus", "Kia Clarus"),
        ("ev6", "Kia EV6"),
        ("joice", "Kia Joice"),
        ("magentis", "Kia Magentis"),
        ("niro", "Kia Niro"),
        ("optima", "Kia Optima"),
        ("picanto", "Kia Picanto"),
        ("proceed", "Kia ProCeed"),
        ("rio", "Kia Rio"),
        ("sephia", "Kia Sephia"),
        ("sorento", "Kia Sorento"),
        ("soul", "Kia Soul"),
        ("sportage", "Kia Sportage"),
        ("stinger", "Kia Stinger"),
        ("stonic", "Kia Stonic"),
        ("venga", "Kia Venga"),
        ("sceed", "Kia SCeed"),
    ],
    "Lamborghini": [
        ("urus-suv", "Lamborghini Urus SUV"),
        ("gallardo-coupe", "Lamborghini Gallardo Coupe"),
    ],
    "Lancia": [
        ("delta", "Lancia Delta"),
        ("thema", "Lancia Thema"),
        ("thesis", "Lancia Thesis"),
        ("ypsilon", "Lancia Ypsilon"),
    ],
    "Land Rover": [
        ("defender", "Land Rover Defender"),
        ("discovery-1", "Land Rover Discovery 1"),
        ("discovery-3", "Land Rover Discovery 3"),
        ("discovery-4", "Land Rover Discovery 4"),
        ("discovery-5", "Land Rover Discovery 5"),
        ("discovery-sport", "Land Rover Discovery Sport"),
        ("freelander", "Land Rover Freelander"),
    ],
    "Lexus": [
        ("ct", "Lexus CT"),
        ("es", "Lexus ES"),
        ("gs", "Lexus GS"),
        ("gx", "Lexus GX"),
        ("is", "Lexus IS"),
        ("lc", "Lexus LC"),
        ("ls", "Lexus LS"),
        ("lx", "Lexus LX"),
        ("nx", "Lexus NX"),
        ("rc", "Lexus RC"),
        ("sc", "Lexus SC"),
        ("ux", "Lexus UX"),
    ],
    "Lincoln": [
        ("corsair", "Lincoln Corsair"),
        ("mkx", "Lincoln MKX"),
        ("navigator", "Lincoln Navigator"),
        ("town-car", "Lincoln Town Car"),
    ],
    "Lotus": [
        ("evora-s-coupe", "Lotus Evora S Coupe"),
    ],
    "Lublin": [
        ("330212-furgon", "Lublin 330212 Furgon"),
    ],
    "Maserati": [
        ("ghibli", "Maserati Ghibli"),
        ("grecale", "Maserati Grecale"),
        ("levante", "Maserati Levante"),
        ("quattroporte", "Maserati Quattroporte"),
    ],
    "Maybach": [
        ("gls", "Maybach GLS"),
        ("s-klasa", "Maybach S klasa"),
    ],
    "Mazda": [
        ("2", "Mazda 2"),
        ("2-demio", "Mazda 2/Demio"),
        ("3", "Mazda 3"),
        ("323f", "Mazda 323F"),
        ("5", "Mazda 5"),
        ("6", "Mazda 6"),
        ("626", "Mazda 626"),
        ("cx-3", "Mazda CX-3"),
        ("cx-30", "Mazda CX-30"),
        ("cx-5", "Mazda CX-5"),
        ("cx-60", "Mazda CX-60"),
        ("cx-7", "Mazda CX-7"),
        ("cx-9", "Mazda CX-9"),
        ("mx-30", "Mazda MX-30"),
        ("mx-5", "Mazda MX-5"),
        ("rx-7", "Mazda RX-7"),
        ("rx-8", "Mazda RX-8"),
    ],
    "McLaren": [
        ("570s-coupe", "McLaren 570S Coupe"),
    ],
    "Mercedes-Benz": [
        ("190", "Mercedes-Benz 190"),
        ("a-klasa", "Mercedes-Benz A klasa"),
        ("amg-gt", "Mercedes-Benz AMG GT"),
        ("b-klasa", "Mercedes-Benz B klasa"),
        ("c-klasa", "Mercedes-Benz C klasa"),
        ("c124", "Mercedes-Benz C124"),
        ("citan", "Mercedes-Benz Citan"),
        ("cl", "Mercedes-Benz CL"),
        ("cla", "Mercedes-Benz CLA"),
        ("clk", "Mercedes-Benz CLK"),
        ("cls", "Mercedes-Benz CLS"),
        ("e-klasa", "Mercedes-Benz E klasa"),
        ("eqa", "Mercedes-Benz EQA"),
        ("eqb", "Mercedes-Benz EQB"),
        ("eqc", "Mercedes-Benz EQC"),
        ("eqe", "Mercedes-Benz EQE"),
        ("eqs", "Mercedes-Benz EQs"),
        ("evito", "Mercedes-Benz eVito"),
        ("g-klasa", "Mercedes-Benz G klasa"),
        ("gl", "Mercedes-Benz GL"),
        ("gla", "Mercedes-Benz GLA"),
        ("glb", "Mercedes-Benz GLB"),
        ("glc", "Mercedes-Benz GLC"),
        ("glc-coupe", "Mercedes-Benz GLC Coupe"),
        ("glk", "Mercedes-Benz GLK"),
        ("gls", "Mercedes-Benz GLS"),
        ("ml", "Mercedes-Benz ML"),
        ("r-klasa", "Mercedes-Benz R klasa"),
        ("s-klasa", "Mercedes-Benz S klasa"),
        ("s124", "Mercedes-Benz S124"),
        ("s63-amg", "Mercedes-Benz S63 AMG"),
        ("sl", "Mercedes-Benz SL"),
        ("slk", "Mercedes-Benz SLK"),
        ("sprinter", "Mercedes-Benz Sprinter"),
        ("t-klasa", "Mercedes-Benz T klasa"),
        ("v-klasa", "Mercedes-Benz V klasa"),
        ("vaneo", "Mercedes-Benz Vaneo"),
        ("viano", "Mercedes-Benz Viano"),
        ("vito", "Mercedes-Benz Vito"),
        ("w123", "Mercedes-Benz W123"),
        ("w124", "Mercedes-Benz W124"),
        ("x", "Mercedes-Benz X"),
    ],
    "MG": [
        ("4-suv", "MG 4 SUV"),
        ("hs-suv", "MG HS SUV"),
    ],
    "Mini": [
        ("clubman", "Mini Clubman"),
        ("countryman", "Mini Countryman"),
        ("hatch", "Mini Hatch"),
    ],
    "Mitsubishi": [
        ("asx", "Mitsubishi ASX"),
        ("carisma", "Mitsubishi Carisma"),
        ("colt", "Mitsubishi Colt"),
        ("eclipse", "Mitsubishi Eclipse"),
        ("eclipse-cross", "Mitsubishi Eclipse Cross"),
        ("galant", "Mitsubishi Galant"),
        ("grandis", "Mitsubishi Grandis"),
        ("i-miev", "Mitsubishi i-MieV"),
        ("l200", "Mitsubishi L200"),
        ("lancer", "Mitsubishi Lancer"),
        ("lancer-evolution", "Mitsubishi Lancer Evolution"),
        ("outlander", "Mitsubishi Outlander"),
        ("pajero", "Mitsubishi Pajero"),
        ("pajero-pinin", "Mitsubishi Pajero Pinin"),
        ("pajero-sport", "Mitsubishi Pajero Sport"),
        ("space-star", "Mitsubishi Space Star"),
    ],
    "Nissan": [
        ("almera", "Nissan Almera"),
        ("altima", "Nissan Altima"),
        ("armada", "Nissan Armada"),
        ("juke", "Nissan Juke"),
        ("leaf", "Nissan Leaf"),
        ("micra", "Nissan Micra"),
        ("murano", "Nissan Murano"),
        ("navara", "Nissan Navara"),
        ("note", "Nissan Note"),
        ("pathfinder", "Nissan Pathfinder"),
        ("patrol", "Nissan Patrol"),
        ("primastar", "Nissan Primastar"),
        ("primera", "Nissan Primera"),
        ("pulsar", "Nissan Pulsar"),
        ("qashqai", "Nissan Qashqai"),
        ("qashqai+2", "Nissan Qashqai +2"),
        ("quest", "Nissan Quest"),
        ("tiida", "Nissan Tiida"),
        ("x-trail", "Nissan X-Trail"),
    ],
    "Opel": [
        ("adam", "Opel Adam"),
        ("agila", "Opel Agila"),
        ("ampera", "Opel Ampera"),
        ("antara", "Opel Antara"),
        ("astra-f", "Opel Astra F"),
        ("astra-g", "Opel Astra G"),
        ("astra-h", "Opel Astra H"),
        ("astra-j", "Opel Astra J"),
        ("astra-k", "Opel Astra K"),
        ("astra-l", "Opel Astra L"),
        ("cascada", "Opel Cascada"),
        ("combo", "Opel Combo"),
        ("corsa-e", "Opel Corsa E"),
        ("corsa-b", "Opel Corsa B"),
        ("corsa-c", "Opel Corsa C"),
        ("corsa-d", "Opel Corsa D"),
        ("corsa-f", "Opel Corsa F"),
        ("corsa-e-f", "Opel Corsa-e F"),
        ("crossland-x", "Opel Crossland X"),
        ("frontera", "Opel Frontera"),
        ("grandland-x", "Opel Grandland X"),
        ("insignia", "Opel Insignia"),
        ("meriva", "Opel Meriva"),
        ("mokka", "Opel Mokka"),
        ("movano", "Opel Movano"),
        ("signum", "Opel Signum"),
        ("tigra-twin-top", "Opel Tigra Twin Top"),
        ("vectra-c", "Opel Vectra C"),
        ("vivaro", "Opel Vivaro"),
        ("zafira-a", "Opel Zafira A"),
        ("zafira-b", "Opel Zafira B"),
        ("zafira-c", "Opel Zafira C"),
        ("zafira-life", "Opel Zafira Life"),
    ],
    "Peugeot": [
        ("1007", "Peugeot 1007"),
        ("106", "Peugeot 106"),
        ("107", "Peugeot 107"),
        ("2008", "Peugeot 2008"),
        ("206", "Peugeot 206"),
        ("207", "Peugeot 207"),
        ("208", "Peugeot 208"),
        ("208-e", "Peugeot 208 E"),
        ("3008", "Peugeot 3008"),
        ("301", "Peugeot 301"),
        ("306", "Peugeot 306"),
        ("307", "Peugeot 307"),
        ("308", "Peugeot 308"),
        ("4008", "Peugeot 4008"),
        ("405", "Peugeot 405"),
        ("406-coupe", "Peugeot 406 Coupe"),
        ("407", "Peugeot 407"),
        ("5008", "Peugeot 5008"),
        ("508", "Peugeot 508"),
        ("607", "Peugeot 607"),
        ("807", "Peugeot 807"),
        ("e-2008", "Peugeot e-2008"),
        ("expert", "Peugeot Expert"),
        ("ion", "Peugeot iON"),
        ("partner", "Peugeot Partner"),
        ("rcz", "Peugeot RCZ"),
        ("rifler", "Peugeot Rifler"),
    ],
    "Porsche": [
        ("911", "Porsche 911"),
        ("boxster", "Porsche Boxster"),
        ("cayenne", "Porsche Cayenne"),
        ("cayenne-coupe", "Porsche Cayenne Coupe"),
        ("cayenne-s", "Porsche Cayenne S"),
        ("macan", "Porsche Macan"),
        ("panamera", "Porsche Panamera"),
    ],
    "Renault": [
        ("arkana", "Renault Arkana"),
        ("austral", "Renault Austral"),
        ("captur", "Renault Captur"),
        ("clio", "Renault Clio"),
        ("espace", "Renault Espace"),
        ("fluence", "Renault Fluence"),
        ("grand-espace", "Renault Grand Espace"),
        ("grand-scenic", "Renault GRAND Scenic"),
        ("kadjar", "Renault Kadjar"),
        ("kangoo", "Renault Kangoo"),
        ("koleos", "Renault Koleos"),
        ("laguna", "Renault Laguna"),
        ("latitude", "Renault Latitude"),
        ("master", "Renault Master"),
        ("megane", "Renault Megane"),
        ("megane-e-tech", "Renault Megane E-Tech"),
        ("modus", "Renault Modus"),
        ("scenic", "Renault Scenic"),
        ("talisman", "Renault Talisman"),
        ("thalia", "Renault Thalia"),
        ("trafic", "Renault Trafic"),
        ("twingo", "Renault Twingo"),
        ("vel-satis", "Renault Vel Satis"),
        ("zoe", "Renault Zoe"),
    ],
    "Rolls Royce": [
        ("dawn", "Rolls Royce Dawn"),
        ("ghost", "Rolls Royce Ghost"),
        ("wraith", "Rolls Royce Wraith"),
    ],
    "Rover": [
        ("200", "Rover 200"),
        ("25", "Rover 25"),
        ("75", "Rover 75"),
    ],
    "SaaB": [
        ("9-2x", "SaaB 9-2X"),
        ("9-3", "SaaB 9-3"),
        ("9-5", "SaaB 9-5"),
        ("9-7", "SaaB 9-7"),
        ("900", "SaaB 900"),
    ],
    "Scion": [
        ("fr-s-coupe", "Scion FR-S Coupe"),
    ],
    "Seat": [
        ("alhambra", "Seat Alhambra"),
        ("altea", "Seat Altea"),
        ("altea-xl", "Seat Altea XL"),
        ("arona", "Seat Arona"),
        ("ateca", "Seat Ateca"),
        ("gordoba", "Seat Gordoba"),
        ("exeo", "Seat EXEO"),
        ("ibiza", "Seat Ibiza"),
        ("leon", "Seat Leon"),
        ("tarraco", "Seat Tarraco"),
        ("toledo", "Seat Toledo"),
    ],
    "Skoda": [
        ("citigo", "Skoda Citigo"),
        ("enyaq", "Skoda Enyaq"),
        ("enyaq-coupe", "Skoda Enyaq Coupe"),
        ("fabia", "Skoda Fabia"),
        ("kamiq", "Skoda Kamiq"),
        ("kadiaq", "Skoda Kadiaq"),
        ("octavia", "Skoda Octavia"),
        ("rapid", "Skoda Rapid"),
        ("roomster", "Skoda Roomster"),
        ("scala", "Skoda Scala"),
        ("superb", "Skoda Superb"),
        ("yeti", "Skoda Yeti"),
    ],
    "Smart": [
        ("forfour", "Smart ForFour"),
        ("fortwo", "Smart Fortwo"),
    ],
    "SsangYong": [
        ("korando", "SsangYong Korando"),
        ("rexton", "SsangYong Rexton"),
        ("tivoli", "SsangYong Tivoli"),
        ("tivoli-grand", "SsangYong Tivoli Grand"),
    ],
    "Subaru": [
        ("brz", "Subaru BRZ"),
        ("forester", "Subaru Forester"),
        ("impreza", "Subaru Impreza"),
        ("legacy", "Subaru Legacy"),
        ("outback", "Subaru Outback"),
        ("trezia", "Subaru Trezia"),
        ("tribeaca-b9", "Subaru Tribeaca B9"),
        ("wrx", "Subaru WRX"),
        ("xv", "Subaru XV"),
    ],
    "Suzuki": [
        ("baleno", "Suzuki Baleno"),
        ("grand-vitara", "Suzuki Grand Vitara"),
        ("jimny", "Suzuki Jimny"),
        ("reno", "Suzuki Reno"),
        ("splash", "Suzuki Splash"),
        ("swace", "Suzuki Swace"),
        ("switch", "Suzuki Switch"),
        ("sx4", "Suzuki SX4"),
        ("sx4-s-cross", "Suzuki SX4 S-cross"),
        ("vitara", "Suzuki Vitara"),
    ],
    "Tesla": [
        ("model-3", "Tesla Model 3"),
        ("model-s", "Tesla Model S"),
        ("model-x", "Tesla Model X"),
        ("model-y", "Tesla Model Y"),
    ],
    "Toyota": [
        ("4_runner", "Toyota 4 Runner"),
        ("auris", "Toyota Auris"),
        ("avalon", "Toyota Avalon"),
        ("avensis", "Toyota Avensis"),
        ("avensis_verso", "Toyota Avensis Verso"),
        ("aygo", "Toyota Aygo"),
        ("aygo_x", "Toyota Aygo X"),
        ("c_hr", "Toyota C-HR"),
        ("camry", "Toyota Camry"),
        ("carina_e", "Toyota Carina E"),
        ("celica", "Toyota Celica"),
        ("corolla", "Toyota Corolla"),
        ("corolla_cross", "Toyota Corolla Cross"),
        ("corolla_verso", "Toyota Corolla Verso"),
        ("fj_cruiser", "Toyota FJ Cruiser"),
        ("gr_yaris", "Toyota GR Yaris"),
        ("gt86", "Toyota GT86"),
        ("highlander", "Toyota Highlander"),
        ("hilux", "Toyota Hilux"),
        ("iq", "Toyota IQ"),
        ("land_cruiser", "Toyota Land Cruiser"),
        ("land_cruiser_hard_top", "Toyota Land Cruiser Hard Top"),
        ("land_cruiser_prado", "Toyota Land Cruiser Prado"),
        ("mr2", "Toyota MR2"),
        ("paseo", "Toyota Paseo"),
        ("prius", "Toyota Prius"),
        ("prius_plus", "Toyota Prius Plus"),
        ("prius_v", "Toyota Prius V"),
        ("proace_city_verso", "Toyota ProAce City Verso"),
        ("rav4", "Toyota Rav 4"),
        ("scion_gt86", "Toyota Scion GT86"),
        ("sequoia", "Toyota Sequoia"),
        ("sienna", "Toyota Sienna"),
        ("tacoma", "Toyota Tacoma"),
        ("tundra", "Toyota Tundra"),
        ("venza", "Toyota Venza"),
        ("verso", "Toyota Verso"),
        ("yaris", "Toyota Yaris"),
        ("yaris_cross", "Toyota Yaris Cross"),
        ("yaris_verso", "Toyota Yaris Verso"),
    ],
    "Volkswagen": [
        ("amarok", "Volkswagen Amarok"),
        ("arteon", "Volkswagen Arteon"),
        ("atlas", "Volkswagen Atlas"),
        ("beetle", "Volkswagen Beetle"),
        ("bora_jetta", "Volkswagen Bora/Jetta"),
        ("caddy", "Volkswagen Caddy"),
        ("corrado", "Volkswagen Corrado"),
        ("crafter", "Volkswagen Crafter"),
        ("cross_optimum", "Volkswagen Cross Optimum"),
        ("crosspolo", "Volkswagen CrossPolo"),
        ("eos", "Volkswagen EOS"),
        ("golf", "Volkswagen Golf"),
        ("golf_plus", "Volkswagen Golf Plus"),
        ("golf_sportsvan", "Volkswagen Golf Sportsvan"),
        ("id3", "Volkswagen ID.3"),
        ("id4", "Volkswagen ID.4"),
        ("jetta", "Volkswagen Jetta"),
        ("lupo", "Volkswagen Lupo"),
        ("multivan", "Volkswagen Multivan"),
        ("new_beetle", "Volkswagen New Beetle"),
        ("passat", "Volkswagen Passat"),
        ("passat_cc", "Volkswagen Passat CC"),
        ("phaeton", "Volkswagen Phaeton"),
        ("polo", "Volkswagen Polo"),
        ("polo_vento", "Volkswagen Polo/Vento"),
        ("polo_classic", "Volkswagen Polo Classic"),
        ("scirocco", "Volkswagen Scirocco"),
        ("sharan", "Volkswagen Sharan"),
        ("t_cross", "Volkswagen T-Cross"),
        ("t_roc", "Volkswagen T-Roc"),
        ("taigo", "Volkswagen Taigo"),
        ("tiguan", "Volkswagen Tiguan"),
        ("tiguan_allspace", "Volkswagen Tiguan Allspace"),
        ("touareg", "Volkswagen Touareg"),
        ("touran", "Volkswagen Touran"),
        ("touran_cross", "Volkswagen Touran Cross"),
        ("transporter", "Volkswagen Transporter"),
        ("up", "Volkswagen UP"),
        ("vento_jetta", "Volkswagen Vento/Jetta"),
    ],
    "Volvo": [
        ("850", "Volvo 850"),
        ("940", "Volvo 940"),
        ("960", "Volvo 960"),
        ("c30", "Volvo C30"),
        ("s40", "Volvo S40"),
        ("s60", "Volvo S60"),
        ("s80", "Volvo S80"),
        ("s90", "Volvo S90"),
        ("v40", "Volvo V40"),
        ("v50", "Volvo V50"),
        ("v60", "Volvo V60"),
        ("v70", "Volvo V70"),
        ("v90", "Volvo V90"),
        ("xc60", "Volvo XC60"),
        ("xc70", "Volvo XC70"),
        ("xc90", "Volvo XC90"),
    ],
}

PRODUCTION_YEAR_CHOICES = [
    ("Wybierz rok produkcji", "Wybierz rok produkcji"),
    ("2024", "2024"),
    ("2023", "2023"),
    ("2022", "2022"),
    ("2021", "2021"),
    ("2020", "2020"),
    ("2019", "2019"),
    ("2018", "2018"),
    ("2017", "2017"),
    ("2016", "2016"),
    ("2015", "2015"),
    ("2014", "2014"),
    ("2013", "2013"),
    ("2012", "2012"),
    ("2011", "2011"),
    ("2010", "2010"),
    ("2009", "2009"),
    ("2008", "2008"),
    ("2007", "2007"),
    ("2006", "2006"),
    ("2005", "2005"),
    ("2004", "2004"),
    ("2003", "2003"),
    ("2002", "2002"),
    ("2001", "2001"),
    ("2000", "2000"),
    ("1999", "1999"),
    ("1998", "1998"),
    ("1997", "1997"),
    ("1996", "1996"),
    ("1995", "1995"),
    ("1994", "1994"),
    ("1993", "1993"),
    ("1992", "1992"),
    ("1991", "1991"),
    ("1990", "1990"),
    ("1989", "1989"),
    ("1988", "1988"),
    ("1987", "1987"),
    ("1986", "1986"),
    ("1985", "1985"),
    ("1984", "1984"),
    ("1983", "1983"),
    ("1982", "1982"),
    ("1981", "1981"),
    ("1980", "1980"),
    ("1979", "1979"),
    ("1978", "1978"),
    ("1977", "1977"),
    ("1976", "1976"),
    ("1975", "1975"),
    ("1974", "1974"),
    ("1973", "1973"),
    ("1972", "1972"),
    ("1971", "1971"),
    ("1970", "1970"),
]

COMPLETE_SET_PRICES = {
    "ETC Zestaw 2D (przód, tył, tunel) - 390 PLN": 390,
    "ETC Zestaw przód 2D - 250 PLN": 250,
    "ETC Zestaw tył 2D - 200 PLN": 200,
    "Nie potrzebuję dywaników tylko matę": 0,
}

MAT_PRICES = {
    "Mata do bagażnika - 300 PLN": 300,
    "Nie potrzebuję маты": 0,
}
