name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.6
        env:
          POSTGRES_USER: ziko
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: shopdjango
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Debug PostgreSQL logs
      run: docker logs $(docker ps -q --filter ancestor=postgres:16.6)

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h postgres -p 5432 -U postgres; do
          echo "Waiting for PostgreSQL..."
          sleep 5
        done

    - name: Run migrations
      run: python manage.py migrate

    - name: Run tests
      run: python manage.py test
